export const banks = [
  { id: 1, value: "MBAPP", name: "Ung dung MobileBanking" },
  { id: 2, value: "VNPAYQR", name: "VNPAYQR" },
  { id: 3, value: "VNBANK", name: "LOCAL BANK" },
  { id: 4, value: "IB", name: "INTERNET BANKING" },
  { id: 5, value: "ATM", name: "ATM CARD" },
  { id: 6, value: "INTCARD", name: "INTERNATIONAL CARD" },
  { id: 7, value: "VISA", name: "VISA" },
  { id: 8, value: "MASTERCARD", name: "MASTERCARD" },
  { id: 9, value: "JCB", name: "JCB" },
  { id: 10, value: "UPI", name: "UPI" },
  { id: 11, value: "VIB", name: "VIB" },
  { id: 12, value: "VIETCAPITALBANK", name: "VIETCAPITALBANK" },
  { id: 13, value: "SCB", name: "Ngan hang SCB" },
  { id: 14, value: "NCB", name: "Ngan hang NCB" },
  { id: 15, value: "SACOMBANK", name: "Ngan hang SacomBank" },
  { id: 16, value: "EXIMBANK", name: "Ngan hang EximBank" },
  { id: 17, value: "MSBANK", name: "Ngan hang MSBANK" },
  { id: 18, value: "NAMABANK", name: "Ngan hang NamABank" },
  { id: 19, value: "VNMART", name: "Ngan hang VnMart" },
  { id: 20, value: "VIETINBANK", name: "Ngan hang Vietinbank" },
  { id: 21, value: "VIETCOMBANK", name: "Ngan hang VCB" },
  { id: 22, value: "HDBANK", name: "Ngan hang HDBank" },
  { id: 23, value: "DONGABANK", name: "Ngan hang Dong A" },
  { id: 24, value: "TPBANK", name: "Ngan hang TPBank" },
  { id: 25, value: "OJB", name: "Ngan hang OceanBank" },
  { id: 26, value: "BIDV", name: "Ngan hang BIDV" },
  { id: 27, value: "TECHCOMBANK", name: "Ngan hang Techcombank" },
  { id: 28, value: "VPBANK", name: "Ngan hang VPBank" },
  { id: 29, value: "AGRIBANK", name: "Ngan hang Agribank" },
  { id: 30, value: "MBBANK", name: "Ngan hang MBBank" },
  { id: 31, value: "ACB", name: "Ngan hang ACB" },
  { id: 32, value: "OCB", name: "Ngan hang OCB" },
  { id: 33, value: "IVB", name: "Ngan hang IVB" },
  { id: 34, value: "SHB", name: "Ngan hang SHB" },
];